services:
  docs:
    image: real_estate_market_place_local_docs
    container_name: real_estate_market_place_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./real_estate_market_place:/app/real_estate_market_place:z
    ports:
      - '9000:9000'
    command: /start-docs
