# Generated by Django 5.0.13 on 2026-06-09 07:31

import auto_prefetch
import core.helpers.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_agentprofile_verification_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRating',
            fields=[
                ('id', models.UUIDField(default=core.helpers.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.PositiveSmallIntegerField(help_text='How well did the agent communicate throughout the transaction?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Communication')),
                ('responsiveness', models.PositiveSmallIntegerField(help_text='How quickly did the agent respond to inquiries?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Responsiveness')),
                ('professionalism', models.PositiveSmallIntegerField(help_text='How professional was the agent in their interactions?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Professionalism')),
                ('value_for_money', models.PositiveSmallIntegerField(help_text='How would you rate the overall value of the service provided by the agent?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Value for Money')),
                ('overall', models.DecimalField(decimal_places=2, editable=False, help_text='The average of the four criteria scores, computed automatically.', max_digits=3, verbose_name='Overall Score')),
                ('review', models.TextField(blank=True, verbose_name='Review')),
                ('agent', auto_prefetch.ForeignKey(help_text='The agent being rated', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.agentprofile')),
                ('rater', auto_prefetch.ForeignKey(help_text='The user who submitted the rating', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Rating',
                'verbose_name_plural': 'Agent Ratings',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('rater', 'agent')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RatingEligibility',
            fields=[
                ('id', models.UUIDField(default=core.helpers.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(help_text="e.g. 'property_enquiry', 'viewing_completed'", max_length=100)),
                ('used', models.BooleanField(default=False, help_text='Flipped to True once the rating is submitted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_eligibilities', to='users.agentprofile')),
                ('rater', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_eligibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating Eligibility',
                'verbose_name_plural': 'Rating Eligibilities',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('rater', 'agent')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
