# Generated by Django 5.0.13 on 2025-09-30 13:18

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproperty',
            name='user',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='agent',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='property.amenity'),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_link',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='property.property'),
        ),
        migrations.AddField(
            model_name='favoriteproperty',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertysubscription',
            name='user',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='lead',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='property.lead'),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='user',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='scheduled_viewing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_scheduled', to='property.propertyviewing'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='propertysubscription',
            unique_together={('user', 'location', 'property_type')},
        ),
        migrations.AddConstraint(
            model_name='propertyviewing',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('property', 'scheduled_time'), name='unique_property_viewing_time'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('user', 'property_link')},
        ),
    ]
