# Generated by Django 5.0.13 on 2025-04-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_listing',
            field=models.CharField(choices=[('Rent', 'Rent'), ('For Sale', 'For Sale')], default='Rent', max_length=200),
        ),
    ]
