# Generated by Django 5.0.13 on 2026-05-13 14:35

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name'], 'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at', '-id'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['order', 'created_at'], 'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['title'], 'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='scheduled_viewing',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the gallery.'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property_link',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='property.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_listing',
            field=models.CharField(choices=[('Rent', 'Rent'), ('For Sale', 'For Sale'), ('Short Let', 'Short Let')], default='Rent', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='lead',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewings', to='property.lead'),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='property.property'),
        ),
        migrations.AlterField(
            model_name='propertyviewing',
            name='user',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to=settings.AUTH_USER_MODEL),
        ),
    ]
