# Generated by Django 5.0.13 on 2026-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_amenity_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(help_text='Size in square feet.'),
        ),
    ]
