# Generated by Django 5.0.13 on 2025-04-21 12:12

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_property_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at'], 'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('penthouse', 'Penthouse'), ('townhouse', 'Townhouse'), ('condo', 'Condominium'), ('land', 'Land'), ('office', 'Office Space'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('farm', 'Farm / Agricultural'), ('other', 'Other')], default='apartment', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Property',
                'verbose_name_plural': 'Favorite Properties',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('user', 'property')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
