# Generated by Django 5.0.13 on 2025-04-30 10:12

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_amenity_options_alter_property_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySubscription',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('studio', 'Studio'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('penthouse', 'Penthouse'), ('townhouse', 'Townhouse'), ('condo', 'Condominium'), ('land', 'Land'), ('office', 'Office Space'), ('shop', 'Shop'), ('warehouse', 'Warehouse'), ('farm', 'Farm / Agricultural'), ('other', 'Other')], max_length=50, null=True)),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Subscription',
                'verbose_name_plural': 'Property Subscriptions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('user', 'location', 'property_type')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
