# Generated by Django 5.0.13 on 2025-05-07 02:53

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_propertysubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='property',
            new_name='property_link',
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='favoriteproperty',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='property.property'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('user', 'property_link')},
        ),
        migrations.CreateModel(
            name='PropertyViewing',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('lead', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='property.lead')),
                ('property', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Viewing',
                'verbose_name_plural': 'Property Viewings',
                'ordering': ['-scheduled_time'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='scheduled_viewing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_scheduled', to='property.propertyviewing'),
        ),
        migrations.AddConstraint(
            model_name='propertyviewing',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('property', 'scheduled_time'), name='unique_property_viewing_time'),
        ),
    ]
