# Generated by Django 5.0.13 on 2026-05-21 07:47

import auto_prefetch
import core.helpers.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.UUIDField(default=core.helpers.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField()),
                ('property', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_featured_listings', to='property.property')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
