# Generated by Django 5.0.13 on 2025-07-23 13:13

import auto_prefetch
import core.helper.media
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCoverImage',
            fields=[
                ('id', models.UUIDField(default=core.helper.models.generate_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=core.helper.media.MediaHelper.get_image_upload_path)),
                ('property', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='property.property')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_cover', to='property.propertycoverimage'),
        ),
    ]
