# Generated by Django 5.0.13 on 2026-05-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_featuredlisting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedListing',
        ),
    ]
