# Generated by Django 5.0.13 on 2026-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_delete_featuredlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_listing',
            field=models.CharField(choices=[('Rent', 'Rent'), ('For Sale', 'For Sale'), ('Short Let', 'Short Let'), ('Hotel', 'Hotel')], default='Rent', max_length=200),
        ),
    ]
