# Generated by Django 5.0.13 on 2025-07-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_cover_image_delete_propertycoverimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at', '-updated_at', '-id'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
