# Generated by Django 5.0.13 on 2026-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_property_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='guest_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of guests.', null=True),
        ),
    ]
