# Generated by Django 5.0.13 on 2026-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', max_length=20, null=True, verbose_name='Auth Provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_field',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_field',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_type',
            field=models.CharField(choices=[('Real Estate Agent', 'Real Estate Agent'), ('Property Manager', 'Property Manager')], max_length=50, verbose_name='Agent Type'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='office_phone_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Denormalised copy of User.phone_number for display purposes.', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
