# Generated by Django 5.0.13 on 2025-04-20 07:01

import core.helper.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agentprofile_agent_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='company_registration_document',
            field=models.FileField(blank=True, null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
