# Generated by Django 5.0.13 on 2026-05-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_provider_user_first_name_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
