# Generated by Django 5.0.13 on 2026-05-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_agentprofile_date_of_birth_agentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience'),
        ),
    ]
