# Generated by Django 5.0.13 on 2025-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_agentprofile_company_registration_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_type',
            field=models.CharField(choices=[('Real Estate Agent', 'Real Estate Agent'), ('Property Manager', 'Property Manager')], max_length=50),
        ),
    ]
