# Generated by Django 5.0.13 on 2026-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_agentprofile_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
    ]
