# Generated by Django 5.0.13 on 2026-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_agentprofile_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('submitted', 'Submitted'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Prospective Buyer/Tenant', 'Prospective Buyer/Tenant'), ('Agent', 'Agent'), ('Admin', 'Admin')], max_length=50, null=True, verbose_name='Role'),
        ),
    ]
