# Generated by Django 5.0.13 on 2025-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Listing', 'New Listing'), ('Price changing', 'Price changing'), ('Message', 'Message'), ('Viewing', 'Viewing'), ('Favorite', 'Favorite'), ('Availability Update', 'Availability Update'), ('Viewing Update', 'Viewing Update')], default='New Listing', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
