# Generated by Django 5.0.13 on 2025-05-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
