# Generated by Django 5.0.13 on 2025-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationpreference_email_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Listing', 'New Listing'), ('Price changing', 'Price changing'), ('Message', 'Message'), ('Viewing', 'Viewing'), ('Favorite', 'Favorite'), ('Availability Update', 'Availability Update'), ('Viewing Update', 'Viewing Update'), ('New Lead', 'New Lead')], default='New Listing', max_length=20),
        ),
    ]
