# Generated by Django 5.0.13 on 2025-04-21 12:12

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0005_alter_amenity_options_alter_property_options_and_more'),
        ('users', '0005_userprofile_max_budget_userprofile_min_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumServiceSubscription',
            fields=[
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='standard', max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscriptions', to='users.agentprofile')),
            ],
            options={
                'verbose_name': 'Premium Service Subscription',
                'verbose_name_plural': 'Premium Service Subscriptions',
                'ordering': ['-start_date'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RentalTransaction',
            fields=[
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_rentals', to=settings.AUTH_USER_MODEL)),
                ('buyer', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_rentals', to=settings.AUTH_USER_MODEL)),
                ('property', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_transactions', to='property.property')),
                ('referred_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Transaction',
                'verbose_name_plural': 'Rental Transactions',
                'ordering': ['-date'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('agent', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='users.agentprofile')),
                ('rental', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='subscriptions.rentaltransaction')),
            ],
            options={
                'verbose_name': 'Agent Commission',
                'verbose_name_plural': 'Agent Commissions',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
