# Generated by Django 5.0.13 on 2025-09-30 13:18

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_initial'),
        ('subscriptions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcommission',
            name='agent',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='agentsubscription',
            name='agent',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='agent',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_properties', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='featuredlisting',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_listings', to='property.property'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Optional link to subscription if payment is for a plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.agentsubscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentaltransaction',
            name='agent',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_rentals', to='users.agentprofile'),
        ),
        migrations.AddField(
            model_name='rentaltransaction',
            name='buyer',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentaltransaction',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_transactions', to='property.property'),
        ),
        migrations.AddField(
            model_name='rentaltransaction',
            name='referred_by',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='rental',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='subscriptions.rentaltransaction'),
        ),
    ]
