# Generated by Django 5.0.13 on 2025-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredlisting',
            name='boost_duration',
            field=models.PositiveIntegerField(default=7, help_text='Boost duration in days'),
        ),
        migrations.AlterField(
            model_name='agentsubscription',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(db_index=True, help_text='Unique transaction reference.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='planconfig',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
