# Generated by Django 5.0.13 on 2026-05-21 07:47

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_featuredlisting'),
        ('subscriptions', '0003_featuredlisting_boost_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlisting',
            name='property',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_featured_listings', to='property.property'),
        ),
    ]
