# Generated by Django 5.0.13 on 2026-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_delete_featuredlisting'),
        ('subscriptions', '0004_alter_featuredlisting_property'),
        ('users', '0006_alter_agentprofile_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredlisting',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='featuredlisting',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='featuredlisting',
            name='boost_duration',
            field=models.PositiveIntegerField(default=7, help_text='Boost duration in days — mirrors plan config at time of boost.'),
        ),
        migrations.AddConstraint(
            model_name='featuredlisting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('property', 'agent'), name='unique_active_boost_per_property_agent'),
        ),
    ]
